'use client';
import { useState } from 'react';
import { signIn } from 'next-auth/react';
import Link from 'next/link';
import { LockKeyhole, ArrowRight, ShieldCheck, Code2, Users, Building2, Eye, EyeOff, LoaderCircle } from 'lucide-react';

const roles=[['student','Developer',Code2],['reviewer','Reviewer',ShieldCheck],['recruiter','Recruiter',Building2]];
export default function LoginPage(){const [role,setRole]=useState('student'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setError('');setBusy(true);const result=await signIn('credentials',{email,password,role,redirect:false,callbackUrl:'/'});setBusy(false);if(result?.error)setError('Email, password, or account type did not match a registered account.');else location.assign('/')}return <main className="auth-page"><section className="auth-card"><Link href="/" className="auth-brand"><span className="brand-mark">CV</span><b>codeveritas<span>.</span></b></Link><div className="auth-eyebrow">SECURE ACCOUNT ACCESS</div><h1>Welcome back.</h1><p className="auth-intro">Sign in to your CodeVeritas workspace.</p><div className="role-tabs" aria-label="Account type">{roles.map(([id,label,Icon])=><button className={role===id?'selected':''} key={id} onClick={()=>setRole(id)}><Icon size={15}/>{label}</button>)}</div><form onSubmit={submit}><label>Email address<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<span className="password-box"><input required type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/><button type="button" aria-label="Show password" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></span></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:null}Sign in <ArrowRight size={15}/></button></form><p className="auth-switch">New to CodeVeritas? <Link href={`/register?role=${role}`}>Create an account</Link></p><div className="role-note"><LockKeyhole size={14}/><span>Reviewer and recruiter access is tied to your account role and requires an organization invite to register.</span></div></section><aside className="auth-aside"><div className="auth-grid-mark"><div/><div/><div/><div/></div><div className="auth-aside-copy"><div className="auth-eyebrow">EVIDENCE OVER ASSERTIONS</div><h2>Your work.<br/>Verified.</h2><p>A trusted technical identity, built from the work you can show.</p><div className="auth-proof"><span><ShieldCheck size={15}/> Verified evidence</span><span><Users size={15}/> Expert review</span><span><Code2 size={15}/> Public repository review</span></div></div><div className="auth-aside-foot">CODEVERITAS <span>·</span> DEVELOPER IDENTITY PROTOCOL</div></aside></main>}


